### ISSUE TITLE
Upgrade vitessce@2 

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/webatlas-app#26]
Open issue to discuss vitessce@2 major point upgrade, and implications with the multi-modal work and paper.

**Comment by davehorsfall** [comment]
@dannda what breaking changes have you encountered in 2.0.2?

**Comment by dannda** [comment]
Apparently version 2 still supports older view configs. But in order to use the new feature Data Types and File Types would need to be updated when building the view config, as well as adding new Coordination Types. 
Currently the View Config API has not been updated for Vitessce v2, so we'd have to write the config JSON from scratch

**Comment by davehorsfall** [comment]
Upgrade performed in `feat-vitessce2` branch, and commit [0c4dd4c](https://github.com/haniffalab/vitessce-app/commit/0c4dd4c530810e2b66892ca38bfae50917db1838). Upgraded config files developed for hindlimb dataset.
